#!/usr/bin/env zsh

# A colourful, pretty version of ls/tree
# https://the.exa.website/
alias le="exa --long --tree --colour-scale --header --group --time-style=long-iso --ignore-glob='*.pyc' --git"

alias md="mkdir -p"

# Laziness yo
alias v="nvim"
alias vi="nvim"

github_clone() {
    [[ -z $1 ]] && echo "Error: ghc requires one argument, e.g. foo/bar" && exit 1
    echo "mkdir -p $(dirname ~/src/github.com/$1)"
    mkdir -p $(dirname ~/src/github.com/$1)
    git clone git@github.com:$1 ~/src/github.com/$1
    cd ~/src/github.com/$1
}

alias ghc=github_clone

fzf_preview() {
    fzf --preview '[[ $(file --mime {}) =~ binary ]] &&
                 echo {} is a binary file ||
                 (bat --style=numbers --color=always {} ||
                  highlight -O ansi -l {} ||
                  coderay {} ||
                  rougify {} ||
                  cat {}) 2> /dev/null | head -500'
}
alias f=fzf_preview

alias kube-nodeports="k get services '-o=custom-columns=NAME:.metadata.name,NODEPORT:.spec.ports[0].nodePort' --no-headers | grep -v '<none>' | sort -k 2n"
